path: C:\Users\*\*\*
train: images\train
val: images\train

#classes
names:
  0: HDMI IN
  1: HDMI OUT
  2: AUDIO OUT 5 PIN DTB
  3: AUDIO IN 5 PIN DTB
  4: RJ-45 LAN
  5: RJ-45 DANTE
  6: RJ-45 POE
  7: AC PWR
  8: DC PWR
  9: USB
  10: USB HID
  11: USB-B
  12: RCA IN
  13: RCA OUT
  14: RJ-45 DM
  15: COM 5 PIN DTB
  16: IR DTB
  17: AUDIO OUT 2 PIN DTB
  18: RELAY DTB
  19: DIG IN DTB
  20: 1/8" TRS IN
  21: RJ-45 SERIAL
  22: 1/8" TRS OUT
  23: RJ-45
  24: USB MINI
  25: XLR 1/4" COMBO
  26: XLR FEMALE
  27: XLR MALE
  28: USB-C
  29: CRESNET DTB
  30: CRESNET 5MM DTB
  31: GPIO 9 PIN DTB
  32: RJ-45 DM IN
  33: RJ-45 DM OUT
  34: SDI IN
  35: SDI OUT
  36: MMF/SC
  37: VGA
  38: USB-B HID
  39: Y/PB/PR/C/COMP
  40: USB-C CONSOLE
  41: USB HOST
  42: USB DEVICE
  43: SFP
  44: USB-C DEVICE
  45: RJ-45 LAN POE
  46: AUDIO OUT LRG
  47: COM 3PIN
  48: DP IN
  49: DP OUT
  50: OPTICAL IN
  51: VGA IN
  52: AUDIO 5MM DTB UNBALANCED
  53: RJ-45 CONTENT
  54: USB-B SERVICE
  55: COM 9PIN
  56: PoDM+
  57: MIC/LINE 3PIN DTB IN
  58: MIC/LINE 3PIN DTB OUT
  59: LINE OUT 3 PIN DTB
  60: RJ-45 HDBT
  61: REMOTE 2 PIN DTB
  62: ALS OUT
  63: AUDIO 12A OUT
  64: USB-B 3.0
  65: USB 3.0
  66: RJ-45 POE+
  67: SPDIF IN
  68: SPDIF OUT
  69: AUDIO I/O DTB
  70: RS-232 DTB
  71: DC PWR OUT
  72: GPIO IN
  73: GPIO OUT
  74: IT DTB OUT
  75: IR DTB IN
  76: Telephone RJ-11
  77: RS-232
  78: RJ-45 AES
  79: 1/4" TRS IN
  80: 1/4" TRS OUT
  81: CRESTRON
  82: QSC
